name: $(Build.SourceBranch)-$(date:yyyyMMdd)$(rev:.r)

trigger:
  branches:
    include:
      - 'development'

pool:
  vmImage: 'ubuntu-latest'

variables:
  - group: Hemmeligheter
  - name: fullSha
    value: '$(Build.SourceVersion)'
  - name: imageName
    value: 'prod-bip/ssb/dapla/klass-subsets-api'

jobs:
  - job: buildTestDockerBuildDockerPush
    displayName: 'Test/build app and Dockerimage'
    steps:
      - task: Maven@3
        displayName: 'Maven install'
        inputs:
          mavenPomFile: 'pom.xml'
          mavenOptions: '-Xmx3072m'
          javaHomeOption: 'JDKVersion'
          jdkVersionOption: '1.11'
          jdkArchitectureOption: 'x64'
          publishJUnitResults: false
          testResultsFiles: '**/TEST-*.xml'
          goals: 'install'
          options: '-DskipTests=true -Dmaven.javadoc.skip=true'
      - task: Docker@2
        displayName: 'Docker build'
        inputs:
          repository: $(imageName)
          command: 'build'
          Dockerfile: 'Dockerfile'
          tags: |
            $(Build.SourceBranchName)-imagescan-$(fullSha)
      - task: Docker@2
        displayName: 'Login to GCR'
        condition: and(succeeded(), ne(variables['Build.Reason'], 'PullRequest'))
        inputs:
          command: login
          containerRegistry: gcrServiceConnection
      - task: Docker@2
        displayName: 'Push image'
        condition: and(succeeded(), ne(variables['Build.Reason'], 'PullRequest'))
        inputs:
          ContainerRegistry: |
            gcrServiceConnection
          repository: $(repoName)
          command: 'push'
          tags: |
            $(Build.SourceBranchName)-imagescan-$(fullSha)
